### ISSUE TITLE
HTTP error 500 when trying to send file from any drive other than C drive

### ISSUE THREAD

**Issue by Buzbee** [FrostySo/Ps4-Pkg-Sender#1]
Seems to be related to file/folder permissions.

**Comment by Buzbee** [comment]
I also can not send 1MB dlc unlockers. It hangs on sending and the ps4 never receives them.

**Comment by FrostySo** [comment]
> Seems to be related to file/folder permissions.

Possibly run it as admin? I have a D drive I send my games from and it seems to work well.

> I also can not send 1MB dlc unlockers. It hangs on sending and the ps4 never receives them.

I've had trouble with this + themes with permanent theme unlockers. I tried using multiple different pkg senders, including just base curl and all produced the same result. I think that's something to do with the pkg installer itself.

**Comment by Buzbee** [comment]
Running as admin disables drag and drop.

**Comment by FrostySo** [comment]
> Running as admin disables drag and drop.

That's odd, I didn't even know. Why would Microsoft do that...

Would you like me to add a context menu for you, right click anywhere to add open the folder browser? 
I'll do so when I get  home. 

In the meantime, try place the program in your other drive, run it and see if it sends. Let me know how it goes!

**Comment by Buzbee** [comment]
I already had UAC disabled. Add menu and i will run as admin and see if it works from H drive then.

**Comment by FrostySo** [comment]
@Buzbee 
[Ps4-Pkg-Sender-WithContextMenu.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5048999/Ps4-Pkg-Sender-WithContextMenu.zip)

Give this a go, just replace put this in the folder with all the dependencies. Let me know how it goes.

This one has context menu added

**Comment by Buzbee** [comment]
I dont see no context menu.

**Comment by Buzbee** [comment]
still http 500 error from H drive with admin rights.

**Comment by FrostySo** [comment]
> I dont see no context menu.

Right click the empty space, it will pop-up. It isn't a file menu item.

**Comment by FrostySo** [comment]
> still http 500 error from H drive with admin rights.

Are you sure it's a file permission related error, or a connection based error. If you check the connections status on the ps4 does it should you an ip address, subnet mask and default gateway? 

I can't help you with this issue. It's something with your computer settings if it's file permission related. 

We just need to debug this step by step to narrow the results down to determine your issue.

**Comment by Buzbee** [comment]
I was assuming http 500 error relates to file/folder permissions. naphalm on psxhax stated "same here! sending from drive any other than C gives me HTTP 500 error. Sending from drive C works fine" I don't have this issue with iref-use's pkg sender but i can only send base packages with it.

**Comment by FrostySo** [comment]
> I was assuming http 500 error relates to file/folder permissions. naphalm on psxhax stated "same here! sending from drive any other than C gives me HTTP 500 error. Sending from drive C works fine" I don't have this issue with iref-use's pkg sender but i can only send base packages with it.

Don't worry, we can easily figure this out. Do you know how to use command prompt to launch applications or run bat files?

I can attach some output that shows the response from the server, then I can take a look when you get the HTTP 500 error.

Also, could you provide the name of the pkg file? The full name would be helpful

**Comment by Buzbee** [comment]
EP1160-CUSA04942_00-GINGERPS40000000-A0100-V0102.pkg I have a computer science degree.

**Comment by Buzbee** [comment]
I tried sending Journey Collection and patch from H. Base would fail with http 500 then patch would hang with "sending" but never actually sent anything to ps4. Copied both to desktop on C and both were sent.

**Comment by FrostySo** [comment]
Sorry, every time I speak technical they don't understand. So I just ask basic and obvious questions to help them understand it. 

[Ps4-Pkg-Sender-Stdout.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5049232/Ps4-Pkg-Sender-Stdout.zip)

Redirect stdout and send me the log. I'll see what I can do based on the output.

**Comment by Buzbee** [comment]
Its been a long time. Can you send me a bat file?

**Comment by Constantine-HD** [comment]
hi ..i use any pkg sender that exist so far and all of the work but with this just get http 500 error..you'r work is perfect ..multi file sender .. progress bar .. unistal pkg (this one so good)..but http 500 error is bed for me...
please fix it and add port chancher cuz i usually send pkg tu 2 or 3 ps4 system in same time and this is impossible in one port

**Comment by FrostySo** [comment]
> Its been a long time. Can you send me a bat file?

Ps4-Pkg-Sender.exe >> debugoutput.txt 

Run this in cmd where cmd is pointed to the same directory it's in. 



> hi ..i use any pkg sender that exist so far and all of them work but with this just get http 500 error..your work is perfect ..multi file sender .. progress bar (this one so good).. unistal pkg ... but http 500 error is bed
> please fix it and add port chancher cuz i usually send pkg tu 2 or 3 ps4 system in same time and this is impossible in one port
> 
> so far just iref-use / ps4-remote-pkg-sender can do this
> 
> love your work keep go on

If you can do the same as above and download Ps4-Pkg-Sender-Stdout.zip just 2 chats up. 


Give me the logs once you see the error popup.

**Comment by Buzbee** [comment]
[debugoutput.txt](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5054554/debugoutput.txt)

I believe Remote Package Sender has problems working after waking up from a sleep with Hen 2.1.3. I powered off before running doing the debug.

**Comment by Buzbee** [comment]
CE-32930-7  SCE_BGFT_ERROR_TASK_NOENT 0x80990019 ?
--

**Comment by FrostySo** [comment]
It says it can't find the file. I really do wish I know why. I'm going to add 1 more output to the sender and hopefully it tells you something. This will print your file location directory.


[Ps4-Pkg-Sender-Stdout.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5054691/Ps4-Pkg-Sender-Stdout.zip)


> ## CE-32930-7 SCE_BGFT_ERROR_TASK_NOENT 0x80990019 ?

The error SCE_BGFT_ERROR_TASK_NOENT means there's no task in the database associated. Which is suppose to happen, as the sender tries to recover the current task before initiating an install.

**Comment by Buzbee** [comment]
Exactly the same but with ::StartServer - Starting server in directory H:\ at the top.
[debugoutput.txt](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5054711/debugoutput.txt)

**Comment by FrostySo** [comment]
> Exactly the same but with ::StartServer - Starting server in directory H:\ at the top.
> [debugoutput.txt](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5054711/debugoutput.txt)

Just H:\ ? 

or 

H:\pathtoyourgame?

What is the path to your game? Is it in the root of H drive?

**Comment by Buzbee** [comment]
root of H drive and its USB if that matters

**Comment by FrostySo** [comment]
> and its USB if that matters

That was the crucial piece of info I needed. Was able to replicate it on my end. Will get back to you to see if it's fixable or not. Maybe Windows handles external drives/usb filepath permissions differently.

**Comment by FrostySo** [comment]
@Buzbee  This has been fixed now. Please test this to ensure it before I release it. 

[Ps4-Pkg-Sender-Fixed.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5056737/Ps4-Pkg-Sender-Fixed.zip)

Also I saw the reply on PSX hax with small DLC files. 

For me it threw 0x80990004 which is SCE_BGFT_ERROR_INVALID_ARGUMENT for some files. I cannot fix it, seems to be an issue with the remote package installer. Some DLC unlockers/theme's work and some don't. I have no idea why. If you'd like to pass that along for them, since I don't have an account and don't plan on making one.

**Comment by Buzbee** [comment]
Yeah it works. Still shows 1.03 though.

As for the small dlc it was already discussed.

@AdamJensen DLC unlockers rarely work for me either. 128kb or 1MB ones. I did get a 1.5MB one to send though. Maybe its Remote package sender's problem with small files.

@Buzbee I don't think so. As I could install the same files using a different sender. 128kb and 1MB ones.

If I remember correctly they have to be OVER 1MB. Maybe you could check size of pkg and if <= 1MB add 1MB padding?

**Comment by Constantine-HD** [comment]
new fix work perfect ... just need 'port selector'
i test tomb_raider_dlc_unlocker.pkg from my archive and it send and install without problem
try add 370 Fpkg to program just for fun and get .net error

**Comment by Constantine-HD** [comment]
new fix work perfect ... just need 'port selector'
i test tomb_raider_dlc_unlocker.pkg from my archive and it send and install without problem
try add 370 Fpkg to program just for fun and get .net error

**Comment by FrostySo** [comment]
> Yeah it works. Still shows 1.03 though.

Yea I didn't change it on purpose lol. I will change it once I get this other issue sorted out.

> If I remember correctly they have to be OVER 1MB. Maybe you could check size of pkg and if <= 1MB add 1MB padding?

Could you send me a pkg file you have that doesn't work and is less than 1mb? I can try add leading 0 bytes to pad 1mb worth and see what happens.


> new fix work perfect ... just need 'port selector'

Port is automatically selected for you. If a port is taken, it will move to the next one. Unless you're talking about something else? 

> try add 370 Fpkg to program just for fun and get .net error
Probably due to out of memory error. The library I use takes up a lot of memory reading the files. I could fix this by reading only the metadata required by hand, but I don't know the structure of the pkg files. 

If you want to import that many files, try doing 20-50 at a time, as the garbage collector should free memory once it goes out of scope of that function.

**Comment by Buzbee** [comment]
I put 2 128kb and 1 1mb in the zip.

[EP3392-CUSA07980_00-The-Dead-Man-DLC-Unlocker.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5060751/EP3392-CUSA07980_00-The-Dead-Man-DLC-Unlocker.zip)

**Comment by FrostySo** [comment]
> I put 2 128kb and 1 1mb in the zip.
> 
> [EP3392-CUSA07980_00-The-Dead-Man-DLC-Unlocker.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5060751/EP3392-CUSA07980_00-The-Dead-Man-DLC-Unlocker.zip)

I added padding with leading 0 bytes. Put it to 1mb, 2mb and 3mb and all failed. Seems to be something wrong with the metadata or structure of the pkg, that the installer seems to refuse.

**Comment by Buzbee** [comment]
@AdamJensen says he used other ps4 senders. Maybe check out their source code.

**Comment by Buzbee** [comment]
Will dlc unlockers work without the game being installed? if remote package sender is receiving them with a notification popup then its good even if they dont install.

**Comment by FrostySo** [comment]
> @AdamJensen says he used other ps4 senders. Maybe check out their source code.

I don't know what he's on about, but I have tried it with every other package sender I could find. Every single one of them resulted in the same thing. Nothing happens.

Maybe ask him to hand over the pkg file that worked for him, then I can re-test. From what I can see here though, it's something to do with the pkg installer.

I think the formatting is invalid because I have had a lot of DLC unlockers work and they were less than 1mb. 

For example, the sekiro theme permanent unlocker (it's pretty much the same as a dlc unlocker) worked fine for me. But then I tried the resident evil 3 theme unlocker and it gave the same error as these pkg files here. I think the pkg installer checks for specific meta data or something.

**Comment by Buzbee** [comment]
GeneX actually said it. I posted him to day which sender and dlc.

**Comment by Buzbee** [comment]
Try this one. The other ones just has sc0 with license.dat, param.sfo, license.info, preserved.dat. this ones different. It also has icon0.png in sc0 and theres a blank Image0/sce_sys folder

[EP9000-CUSA00004_00-UNLOCKCOLEMISSIO_COLES_LEGACY_DLC.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5060996/EP9000-CUSA00004_00-UNLOCKCOLEMISSIO_COLES_LEGACY_DLC.zip)

**Comment by FrostySo** [comment]
> Try this one. The other ones just has sc0 with license.dat, param.sfo, license.info, preserved.dat. this ones different. It also has icon0.png in sc0 and theres a blank Image0/sce_sys folder
> 
> [EP9000-CUSA00004_00-UNLOCKCOLEMISSIO_COLES_LEGACY_DLC.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5060996/EP9000-CUSA00004_00-UNLOCKCOLEMISSIO_COLES_LEGACY_DLC.zip)

This one worked fine. 

I'm not sure how to programatically add all that in though, I will take a look at the ps4_tools library and see what I can do. If adding those in will help, then so be it.

**Comment by Buzbee** [comment]
I just opened them up with orbis-pub-chk.exe and viewed their contents.

**Comment by Buzbee** [comment]
EP9000-CUSA00194_00-UDAWNDLC00000001_PREORDER_DLC.pkg in the first zip is larger and has the same dir structure as Coles legacy. That one failed? Wonder whats different.

**Comment by FrostySo** [comment]
I couldn't tell ya. It's for sure a weird problem lol

**Comment by FrostySo** [comment]
The error comes from bgft_download_register_package_task function. He has EPRINTF statements everywhere, so I think Mira may be able to catch these. Tomorrow I will test this, unless you want to. 

Just need to see what it says in the logger, then we may be able to narrow it down and fix it.

the json response is as follows

{"status": "fail", "error_code": 0x80990004 }

**Comment by Buzbee** [comment]
@Buzbee I used Irefuse because is the fastest/simplest UI that handle multiples files.
But my last resource, that never failed me are the .bat files here.
And the last DLC Unlockers that I remember that failed were the Ghost Recon Wildlands.

Apart from those DLCs frostyso sender has been very helpful. Yesterday it was being funny with Mass Effect Andromeda, but other senders were too and I could only install it using the .bat files.

here are the bat filles
[pkg sender.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5062626/pkg.sender.zip)

**Comment by FrostySo** [comment]
> @Buzbee I used Irefuse because is the fastest/simplest UI that handle multiples files.
> But my last resource, that never failed me are the .bat files here.
> And the last DLC Unlockers that I remember that failed were the Ghost Recon Wildlands.
> 
> Apart from those DLCs frostyso sender has been very helpful. Yesterday it was being funny with Mass Effect Andromeda, but other senders were too and I could only install it using the .bat files.
> 
> here are the bat filles
> [pkg sender.zip](https://github.com/FrostySo/Ps4-Pkg-Sender/files/5062626/pkg.sender.zip)

the .bat files are the same as any other sender. There's only 1 api. I do think though I screwed up as the is_exists api call checks through title ID, which would not install DLC if you had the game installed already since it "already exists". I have fixed this and will push it out once I figure out the other thing. 

I checked the code for iref-use and it uses the same methods, just uses the p2p protocol instead of http.

**Comment by FrostySo** [comment]
Closing. Refer to #2  if you wan to continue this talk. The main issue for this issue has been resolved.

**Comment by poplol173** [comment]
i do have the same error, no clue what does it
